[fix] 배포 Redis 설정 문제 해결
* fix: dockerfile 내 doppler 설정 삭제

* fix: deploy.yml에서 도플러 관련 설정 진행

* fix: doppler cli 없을때만 설치

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,14 +54,6 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      #환경 변수
-      #도플러 변경 예정
-      # - name: application-secret 추가
-      #   env:
-      #     ACTIONS_STEP_DEBUG: true
-      #     APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET }}
-      #   run: echo "$APPLICATION_SECRET" > src/main/resources/application-secret.yml
-
       - name: Docker Buildx 설치
         uses: docker/setup-buildx-action@v2
 
@@ -87,8 +79,6 @@ jobs:
         with:
           context: ./backend
           push: true
-          build-args: |
-            DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }}
           cache-from: type=registry,ref=ghcr.io/${{ steps.export_owner.outputs.owner_lc }}/${{ steps.export_image.outputs.image_name }}:cache
           cache-to: type=registry,ref=ghcr.io/${{ steps.export_owner.outputs.owner_lc }}/${{ steps.export_image.outputs.image_name }}:cache,mode=max
           tags: |
@@ -124,10 +114,28 @@ jobs:
           working-directory: /
           comment: Deploy
           command: |
+            if ! command -v doppler &> /dev/null
+                        then
+                            echo "Doppler CLI not found. Installing now..."
+                            # (Debian/Ubuntu 기준 설치 명령어)
+                            curl -sLf --retry 3 --tlsv1.2 --proto "=https" '...' | sudo gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg && \
+                            echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list && \
+                            sudo apt-get update && \
+                            sudo apt-get -y install doppler
+            else
+               echo "Doppler CLI is already installed."
+            fi && \
+
+            export DOPPLER_TOKEN="${{ secrets.DOPPLER_TOKEN }}" && \
             docker pull ghcr.io/${{ needs.buildImageAndPush.outputs.owner_lc }}/${{ needs.buildImageAndPush.outputs.image_name }}:latest && \
+            
             docker stop app1 2>/dev/null || true && \
             docker rm app1 2>/dev/null || true && \
+
+            export DOPPLER_TOKEN="${{ secrets.DOPPLER_TOKEN }}" && \
+            doppler run --project waitfair --config prd -- \
              docker run -d --name app1 --network common -p 8080:8080 \
-              -e DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} \
               ghcr.io/${{ needs.buildImageAndPush.outputs.owner_lc }}/${{ needs.buildImageAndPush.outputs.image_name }}:latest && \
+            
+            unset DOPPLER_TOKEN && \
             docker image prune -f          
